apiVersion: acmp.corp/v1
kind: NamespaceRequest
metadata:
  name: tenant8
spec:
  cluster: dev01
  memory: 10
---
## some comments that needs to be preserverd
## please when updating the file don't remove me
